# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2ccc509b9d4f1cc7e806f383238d73a0"
name = "remove-product-from-checkout"
application_url = "https://dense-dust-respondent-head.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "mehul-checkout-extensions.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://dense-dust-respondent-head.trycloudflare.com/auth/callback",
  "https://dense-dust-respondent-head.trycloudflare.com/auth/shopify/callback",
  "https://dense-dust-respondent-head.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
